# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Breyta < Formula
  desc "Command-line interface for working with Breyta flows"
  homepage "https://flows.breyta.ai"
  version "2026.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/breyta/breyta-cli/releases/download/v2026.6.1/breyta_2026.6.1_darwin_amd64.tar.gz"
      sha256 "e07efdd0afb1960688b0966209b9384656577e758e0ca670ebc74bdfc24e57fd"

      define_method(:install) do
        bin.install "breyta"
        bin.install "parinfer-rust"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/breyta/breyta-cli/releases/download/v2026.6.1/breyta_2026.6.1_darwin_arm64.tar.gz"
      sha256 "5baf26d429672db0fc7b1c49d6d8996fb2c9f4ec2de40932cbc62294bee6779c"

      define_method(:install) do
        bin.install "breyta"
        bin.install "parinfer-rust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/breyta/breyta-cli/releases/download/v2026.6.1/breyta_2026.6.1_linux_amd64.tar.gz"
      sha256 "e78c08c525b78b6f9b3ee5cab8eb1fbd310603ab4dc81f278f62bbaffb5b2c87"
      define_method(:install) do
        bin.install "breyta"
        bin.install "parinfer-rust"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/breyta/breyta-cli/releases/download/v2026.6.1/breyta_2026.6.1_linux_arm64.tar.gz"
      sha256 "cfa112dc365282f394f8adc15167834129359b65bf1520b12c3b32e2c0a5cd28"
      define_method(:install) do
        bin.install "breyta"
        bin.install "parinfer-rust"
      end
    end
  end

  test do
    system "#{bin}/breyta", "version"
  end
end
