# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Breyta < Formula
  desc "Command-line interface for working with Breyta flows"
  homepage "https://flows.breyta.ai"
  version "2026.7.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/breyta/breyta-cli/releases/download/v2026.7.5/breyta_2026.7.5_darwin_amd64.tar.gz"
      sha256 "4ba4c6b4e7b90e67d700905f926093d7b7520ee0e22e86e133e0f9edd68ce042"

      define_method(:install) do
        bin.install "breyta"
        bin.install "parinfer-rust"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/breyta/breyta-cli/releases/download/v2026.7.5/breyta_2026.7.5_darwin_arm64.tar.gz"
      sha256 "572a1632913f41e5f0bb928cd789c2640705d5427c23eab336560622d736faa4"

      define_method(:install) do
        bin.install "breyta"
        bin.install "parinfer-rust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/breyta/breyta-cli/releases/download/v2026.7.5/breyta_2026.7.5_linux_amd64.tar.gz"
      sha256 "e98a5633a672c23ea79409b1b2609fd23b4749dc24ac60031b60d138c99baa9f"
      define_method(:install) do
        bin.install "breyta"
        bin.install "parinfer-rust"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/breyta/breyta-cli/releases/download/v2026.7.5/breyta_2026.7.5_linux_arm64.tar.gz"
      sha256 "057a2e601c979cba8d4d264110a38708f2710b65d51dae7636f064e793b2abc3"
      define_method(:install) do
        bin.install "breyta"
        bin.install "parinfer-rust"
      end
    end
  end

  test do
    system "#{bin}/breyta", "version"
  end
end
